kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: trxbase/hivemq-decoupled-config
      tags: 
        - latest 
        - 2023.1




