version: '3.8'

networks:
  default:
    name: traefik-default

services:
  hivemq:
    container_name: $COMPOSE_PROJECT_NAME
    image: trxbase/hivemq-decoupled-config:2023.1
    ports:
      - 1883:1883
    restart: unless-stopped