version: "3.8"

networks:
  default:
    name: hivemq-network

services:
  hivemq:
    container_name: $COMPOSE_PROJECT_NAME
    image: trxbase/hivemq-decoupled-config:latest
    ports:
      - 1883:1883
    restart: unless-stopped
